# 公共配置文件
spring:
  application:
    name: nutrition-platform
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nutrition_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # Redis 配置
  # todo 需替换配置，然后取消注释
  #  redis:
  #    database: 1
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "营养搭配服务平台接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zcw.springbootinit.controller

# 营养搭配平台配置
nutrition:
  # JWT配置
  jwt:
    secret: nutrition-platform-secret-key-2024
    expiration: 86400000  # 24小时，单位毫秒
  # 营养计算配置
  calculation:
    # 基础代谢率计算公式类型 (Harris-Benedict, Mifflin-St Jeor)
    bmr-formula: Mifflin-St Jeor
    # 活动系数
    activity-factors:
      sedentary: 1.2      # 久坐
      light: 1.375        # 轻度活动
      moderate: 1.55      # 中度活动
      active: 1.725       # 重度活动
      very-active: 1.9    # 极重度活动
  # 文件上传配置
  upload:
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif
